title: "Layer8 Linux"
description: "A beginner-friendly Linux distribution with up-to-date software on an LTS kernel."
theme: null
markdown: kramdown

# Navigation links
nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Download
    link: /download
  - name: Documentation
    link: /documentation
  - name: Contribute
    link: /contribute
  - name: Community
    link: /community
